### ISSUE TITLE
Need ncurses to run salticid

### ISSUE THREAD

**Issue by selenamarie** [aphyr/salticid#10]
I ran into this today on a RHEL6 box: 

[selena@]$ salticid -s salticid
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- ncurses (LoadError)
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/lib/ruby/gems/1.8/gems/salticid-0.9.5/bin/../lib/salticid/interface.rb:3
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/lib/ruby/gems/1.8/gems/salticid-0.9.5/bin/salticid:6
        from /usr/bin/salticid:19:in `load'
        from /usr/bin/salticid:19

I needed the following packages: 
- ncurses-devel
- ruby-devel
- "Developer Tools" 

And, I needed to install the ncurses gem. 

Is this a doc change, or is adding ncurses to the pre-reqs something you want to do? Or something else?

**Comment by jeteon** [comment]
I get a similar thing but for "curses" instead on Kubuntu 15.10. 

```
gem install curses
```

Fixes it. Undocumented dependency? Or is it something deeper in how my Ruby is configured versus how it generally is?
