### ISSUE TITLE
Fail to run the first demo?

### ISSUE THREAD

**Issue by UncP** [aphyr/salticid#16]
This is the first demo example.rb

    host '127.0.0.1' do
      user 'localhost'
        task :hello do
          exec! 'ls -la /', echo: true
      end
    end

I type `salticid -l example.rb -h localhost hello` in the command line, but get this

![1](https://user-images.githubusercontent.com/16263931/28056322-2d92996c-664f-11e7-8af3-3a607aaddd61.png)

BTW, this is my `/etc/hosts`

    127.0.0.1	localhost
    127.0.1.1	UncP

**Comment by aphyr** [comment]
You'll need to scroll up to see the error message; this part of the stacktrace isn't useful. I suspeeect you may have the wrong username: is your user *really* named "localhost"?

**Comment by UncP** [comment]
I changed the demo to this:

    host '127.0.0.1' do
      user 'UncP'
        task :hello do
          exec! 'ls -la /', echo: true
      end
    end

I type `salticid -l example.rb -h UncP hello` in the command line, but get **connection refused**.

![1](https://user-images.githubusercontent.com/16263931/28098829-259bf2b6-66eb-11e7-9ae2-ac09eda352de.png)

How can i fix this?

**Comment by UncP** [comment]
By the way, i am an intern at [PingCAP](https://github.com/pingcap), i am helping my company to create jepsen test for our distributed database [TiDB](https://github.com/pingcap/tidb), which is like CockroachDB. So my job is to modify cockroach jepsen test to make it work for TiDB, so is salticid realy necessary for me?

**Comment by aphyr** [comment]
Your stacktrace says "127.0.1.1", not "127.0.0.1", so that might be part of it. Since your connection was refused, I'd guess you're not running an SSH server on 127.0.1.1.

You don't need salticid for Jepsen any more--it's been gone for a couple years at least, and there's no salticid in the cockroach tests. See the Jepsen documentation.

**Comment by UncP** [comment]
Ok, thanks for your reply.
